obstacle_range: 3.5
raytrace_range: 10.0
#max_obstacle_height: 1.0
footprint: [[0.25, 0.18], [0.25, -0.18], [-0.25, -0.28], [-0.25, 0.18]]
#robot_radius: ir_of_robot
inflation_radius: 0.70

map_type: voxel

observation_sources: point_cloud_sensor

#laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: base_link, data_type: PointCloud2, topic: cloud_transformed, marking: true, clearing: true, max_obstacle_height: 1.0, min_obstacle_height: 0.03}
